

Spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chatting?serverTimezone=Asia/Seoul
    #    url: jdbc:mysql://mysql_container:3306/matching?serverTimezone=Asia/Seoul
    #    username: ${MYSQL_NAME}
    #    password: ${MYSQL_PASSWORD}
    username: root
    password: 1234





